import os, sys, glob

Import('env')

sourceFiles = Split('cassandra_constants.cpp  Cassandra.cpp  cassandra_types.cpp')

thriftcassandra = env.StaticLibrary('thriftcassandra', sourceFiles)

Export('thriftcassandra')
