import os, sys

Import('env')
Import('deplibs')

deplibs += Split('thrift boost_system boost_thread pthread')
sourceFiles = Split('example_simple.cpp')

example_simple = env.Program('example_simple', sourceFiles, LIBS=deplibs)

examples = example_simple
Export('examples')
